### PR TITLE
Trigger handlers when events are fired on child elements

### PR DESCRIPTION
**Pull request by liudangyi**
Fix the bug that ujs won't handle events when clicking on the following link

    <a data-confirm="Sure?"><strong>Destroy</strong></a>

It's a mistake by me, which is quite disastrous.

### CODE REVIEW

**Comment by liudangyi** [comment]
I'm a little worried about the release process. Should I also include the dist file in the commit?

**Comment by guilleiguaran** [comment]
@liudangyi yes, I think having the dist file updated is a good idea since devs using it from github (with npm/yarn and soon with bundler) would be able to get last version without having to wait for a new release

**Comment by matthewd** [comment]
> with npm/yarn and soon with bundler

Ugh :confused:

Action Cable works with bundler without needing a committed dist file at all. Can npm/yarn not do that? 😟

**Comment by guilleiguaran** [comment]
@matthewd now that this is a gem probably we can make it work exactly as ActionCable. Right now to use the source version of the assets users should require the full entry path manually:

```
//= require rails-ujs/src/rails-ujs
```

That is because having just `//= require rails-ujs` it will try to load the file referenced in the main key of the package.json/bower.json.


Another idea:

For users of Sprockets + npm/Yarn we can add an index.js to the repository and the require to main entry file on this:

```
// index.js
//= require ./src/rails-ujs
```

This will make the `//= require rails-ujs` work using npm/Yarn + the lib from github if we decide to exclude the dist file from the repository

We can exclude that index.js from the distributed packages so it won't affect to users of the npm/bower package.

**Comment by guilleiguaran** [comment]
One small disadvantage of the approach used by Action Cable is that `coffee_script` is a hard dependency when you're using it from github or a local path:

If you generate a new app combining `--edge` (or `--dev`) and `--skip-coffee` options

```
% rails/railties/exe/rails new baz --skip-coffee --edge
```

You will get an error trying to retrieve `application.js` asset:

```
LoadError: cannot load such file -- coffee_script
```

But I guess this not a big deal since it won't happen to final users.

**Pull request merged**
